### ISSUE TITLE
Exercise - 2 cannot be solved without try and except.

### ISSUE THREAD

**Issue by sabbir-ahmed16** [eftekhar-hossain/Teaching#1]
- Both of the solutions provided during class gave wrong output for some edge cases.
- `type(score) == str` or `isinstance(score, str)` functions return `True` irrespective of the type of input being provided.
- One way left for checking if the input is convertible to float or not before is to use `isnumeric()` function but it gives `False` for floating value.
![is_numeric](https://user-images.githubusercontent.com/53910540/132533380-17d95257-00f7-40d7-974e-d74136282f54.PNG)
![is_numeric2](https://user-images.githubusercontent.com/53910540/132533419-510deef5-a277-43f6-8565-478baaf40851.PNG)

**Comment by eftekhar-hossain** [comment]
I get your findings. The program definitely needs a try-except block.  It works perfectly when we assign the values within a variable instead of taking input from the user.
